<?php 
    if(is_front_page())
    {
        get_template_part('template-parts/sidebar/home','sidebar');
    }
    else
    {
        get_template_part('template-parts/sidebar/site','sidebar');
    }
?>
